FROM  mcr.microsoft.com/dotnet/sdk:8.0-alpine
WORKDIR /App
COPY . ./ 

WORKDIR /Test
COPY . .

RUN apk update
RUN apk add git


WORKDIR /App/docker-test-folder
RUN git init
WORKDIR /App
ENTRYPOINT ["dotnet", "run", "-p /App/docker-test-folder"]