FROM  mcr.microsoft.com/dotnet/sdk:9.0-alpine
WORKDIR /App
COPY . ./ 

RUN apk update
RUN apk add git

WORKDIR /App/docker-test-folder
RUN git init
RUN git config --global user.email "markjameshoward@hotmail.co.uk"
RUN git config --global user.name "Mark Howard"

WORKDIR /App
ENTRYPOINT ["tail", "-f", "/dev/null"]